name: Plugin Feature

inputs:
  - name: featureName
    description: "Feature Name"
    type: string
  - name: tests
    description: "Include Tests?"
    type: boolean
    default: true

files:
  - source: feature.njk
    destination: src/features/${{ inputs.featureName | wpClassFilename }}.php
  - source: test.njk
    if: ${{ inputs.tests }}
    destination: tests/features/test-${{ inputs.featureName | wpClassFilename }}.php
