name: create-wordpress-plugin@feature

inputs:
  - name: featureName
    description: "Feature Name"
    type: string
  - name: tests
    description: "Include Tests?"
    type: boolean
    default: true

files:
  - source: feature.stub
    destination: src/features/${{ inputs.featureName | wpClassFilename }}
  - source: test.stub
    if: ${{ inputs.tests }}
    destination: tests/Features/${{ inputs.featureName | psrClassFilename('', 'Test.php') }}
