name: Built Release

on:
  push:
    branches:
      - develop
      - main
      - production

jobs:
  built-release:
    uses: alleyinteractive/.github/.github/workflows/built-release.yml@main
    with:
      node: 20
