name: Create a -built branch

on:
  push:
    branches:
      - main
      - develop
      - reusable

jobs:
  built-branch:
    uses: alleyinteractive/.github/.github/workflows/built-branch.yml@workflows
