name: Create a -built branch

on:
  push:
    branches:
      - main
      - develop
      - set-output

jobs:
  built-branch:
    uses: alleyinteractive/.github/.github/workflows/built-branch.yml@set-output
