name: Create a -built tag

on:
  push:
    tags:
      - 'v*.*.*'
      - '!*-built'

jobs:
  built-branch:
    name: Create Built Release
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        node: [16]

    steps:
      - uses: actions/checkout@v3
      - name: Clear previous vendor
        shell: bash
        run: rm -rf vendor && rm -rf composer.lock
      - name: Check if the plugin has front-end assets
        shell: bash
        id: has-node-assets
        run: |
          [[ -f package.json ]] && echo "::set-output name=exists::true" || echo "::set-output name=exists::false"
      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php }}
          version: 2
          args: --prefer-dist --no-dev
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install node dependencies (npm ci)
        if: steps.has-node-assets.outputs.exists == 'true'
        run: npm install
      - name: Run npm build
        if: steps.has-node-assets.outputs.exists == 'true'
        run: npm run build
      - name: Extract branch name
        shell: bash
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
        id: vars
      - name: Push to -built branch
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BUILT_BRANCH: '${{ steps.vars.outputs.tag }}-built'
          TAG_NAME: '${{ steps.vars.outputs.tag }}-built'
        run: |
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config --global user.name "$GITHUB_ACTOR"

          rm -rf .gitignore docker_tag output.log .github
          mv .deployignore .gitignore

          git checkout -b $BUILT_BRANCH

          git add -A && git commit -m "Built changes for $TAG_NAME"

          git tag -a "$TAG_NAME" -m "Build assets for $TAG_NAME"
          git push origin "refs/tags/$TAG_NAME"
