name: Create a -built branch

on:
  push:
    branches:
      - main
      - develop

jobs:
  built-branch:
    name: Built Branch
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [8.0]
        node: [16]

    steps:
      - uses: actions/checkout@v3
      - name: Clear previous vendor
        shell: bash
        run: rm -rf vendor
      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php }}
          version: 2
          args: --prefer-dist --no-dev
      - name: Check if the plugin has front-end assets
        shell: bash
        id: has-node-assets
        run: |
          [[ -f package.json ]] && echo "::set-output name=exists::true" || echo "::set-output name=exists::false"
      - name: Setup Node
        if: steps.has-node-assets.outputs.exists == 'true'
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install node dependencies (npm ci)
        if: steps.has-node-assets.outputs.exists == 'true'
        run: npm install
      - name: Run npm build
        if: steps.has-node-assets.outputs.exists == 'true'
        run: npm run build
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Push to -built branch
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BUILT_BRANCH: '${{ steps.extract_branch.outputs.branch }}-built'
        run: |
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config --global user.name "$GITHUB_ACTOR"

          rm -rf .gitignore docker_tag output.log .github
          mv .deployignore .gitignore

          git checkout -b $BUILT_BRANCH

          git add -A && git commit -m "Changes from $GITHUB_SHA"
          git push --force -u origin "${BUILT_BRANCH}"
