name: Create a -built tag

on:
  push:
    tags:
      - 'v*.*.*'
      - '!*-built'
      - 'set-output-test-*'

jobs:
  built-tag:
    uses: alleyinteractive/.github/.github/workflows/built-tag.yml@set-output
