name: Built Release

on:
  push:
    branches:
      - develop
      - main
      - production

jobs:
  built-release:
    uses: alleyinteractive/.github/.github/workflows/built-release.yml@main
    if: ${{ github.repository }} != 'alleyinteractive/create-wordpress-plugin'
    with:
      node: 16
