name: Linting Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  code-quality:
    name: Composer PHPCS and PHPStan
    uses: alleyinteractive/.github/.github/workflows/php-composer-command.yml@composer-command
    with:
      php: 8.1
      command: |
        phpcs
        phpstan
