name: Coding Standards

on:
  push:
    branches:
      - develop
  pull_request:
  # Uncomment and edit the following to run on a schedule.
  # schedule:
  #   - cron: '0 5 * * 0' # Run once per week at 5am UTC on Sundays.

jobs:
  coding-standards:
    uses: alleyinteractive/.github/.github/workflows/php-coding-standards.yml@main
    with:
      php: '8.2'
