name: Node Tests

on:
  push:
    branches:
      - develop
  pull_request:
  # Uncomment and edit the following to run on a schedule.
  # schedule:
  #   - cron: '15 5 * * 0' # Run once per week at 5:15am UTC on Sundays.

jobs:
  node-tests:
    uses: alleyinteractive/.github/.github/workflows/node-tests.yml@main
    with:
      node: 20
      run-audit: true
