name: Node Tests

on:
  push:
    branches:
      - develop
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  node-tests:
    uses: alleyinteractive/.github/.github/workflows/node-tests.yml@set-output
    with:
      run-audit: true
