name: Node Tests

on:
  push:
    branches:
      - develop
  pull_request:

jobs:
  node-tests:
    uses: alleyinteractive/.github/.github/workflows/node-tests.yml@main
    with:
      run-audit: true
