name: Node Tests

on:
  pull_request:

jobs:
  npm-ci:
    name: Install, build, and test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        node: [16]
    steps:
      - name: Cancel previous runs of this workflow (pull requests only)
        if: ${{ github.event_name == 'pull_request' }}
        uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: ${{ github.token }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check if the plugin has front-end assets
        shell: bash
        id: has-node-assets
        run: |
          [[ -f package.json ]] && echo "::set-output name=exists::true" || echo "::set-output name=exists::false"
      - name: Setup Node
        if: steps.has-node-assets.outputs.exists == 'true'
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install node dependencies (npm ci)
        if: steps.has-node-assets.outputs.exists == 'true'
        run: npm install
      - name: Run npm test
        if: steps.has-node-assets.outputs.exists == 'true'
        run: npm run test
      - name: Run npm lint
        if: steps.has-node-assets.outputs.exists == 'true'
        run: npm run lint
      - name: Run npm build
        if: steps.has-node-assets.outputs.exists == 'true'
        run: npm run build
