name: Update WordPress Plugin

on:
  pull_request:
  schedule:
    - cron: '0 */6 * * *'

permissions:
  contents: write
  pull-requests: write

jobs:
  update-plugin:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: alleyinteractive/action-update-wordpress-plugin@feature
      with:
        plugin-file: 'plugin.php'
        upgrade-npm-dependencies: "true"
