name: Update WordPress Plugin

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

permissions:
  contents: write
  pull-requests: write

jobs:
  update-plugin:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: alleyinteractive/action-update-wordpress-plugin@22003e4d0e5d3a086095bf9600ecd470db694cf8
      with:
        plugin-file: 'plugin.php'
        upgrade-npm-dependencies: "true"
